apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: appropriate-camel-go
  janus-idp.io/tekton: appropriate-camel-go
  backstage.io/kubernetes-id: appropriate-camel-go
  backstage.io/kubernetes-namespace: rhtap-e2e-demo 
  app.kubernetes.io/part-of: appropriate-camel-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
